### ISSUE TITLE
GFX4D Raises "Soft WDT reset"

### ISSUE THREAD

**Issue by rei-vilo** [4dsystems/GFX4d#1]
The GFX4D library raises a `Soft WDT reset`.

See 

* https://github.com/esp8266/Arduino/issues/2866 
* https://forum.arduino.cc/index.php?topic=442570.0

**Comment by pauleilio** [comment]
Could you please confirm which GFX4d function causes the soft WDT reset and how it is being used.

**Comment by rei-vilo** [comment]
Two cases:

* when using touch
* when using GRAM

**Comment by pauleilio** [comment]
Are they both blocking in their use, and if they are blocking eg, touch in a loop waiting for a response,
is a yield(); being called, within.

**Comment by rei-vilo** [comment]
I solved the issue by replacing 

`delayMicroseconds(50);`

by

`delay(1);`

as mentioned in the link I provided.

**Comment by pauleilio** [comment]
Is the delay necessary or could you replace it with a `yield();`

**Comment by rei-vilo** [comment]
Sorry, I am not an expert in ESP8266, neither am I the developer of this library.

**Comment by pauleilio** [comment]
I am sorry, so was the delay added to the library in the touchupdate function. This shouldn't be necessary.

If a touch response is being checked for like this
`while(gfx.touch_GetPen() != TOUCH_PRESSED)`
it will certainly cause a soft WDT reset as the ESP8266 is not allowed to carry out it's necessary task's
A better way would be
`while(gfx.touch_GetPen() != TOUCH_PRESSED){`
`yield();`
`}`

**Comment by pauleilio** [comment]
It isn't necessary to add any delays or yielding to the touch_Update() function
`while(gfx.touch_Update)`
works without any additional yield
A main loop yield should be sufficient in most circumstances. yield is included in library functions that require it.
