### ISSUE TITLE
GFX4d [-Werror=return-type]

### ISSUE THREAD

**Issue by christianfunginet** [4dsystems/GFX4d#3]
Hi dears:
I'm having this error after update library

C:\Users\christian\Documents\Arduino\libraries\GFX4d\src\GFX4d.cpp: In member function 'int16_t GFX4d::ImageTouchedAuto(int)':
C:\Users\christian\Documents\Arduino\libraries\GFX4d\src\GFX4d.cpp:4820:1: error: control reaches end of non-void function [-Werror=return-type]
 4820 | }
      | ^
C:\Users\christian\Documents\Arduino\libraries\GFX4d\src\GFX4d.cpp: In member function 'uint16_t GFX4d::GetSliderValue(uint16_t, uint8_t, uint16_t, uint16_t, uint16_t)':
C:\Users\christian\Documents\Arduino\libraries\GFX4d\src\GFX4d.cpp:4855:1: error: control reaches end of non-void function [-Werror=return-type]
 4855 | }
      | ^

**Comment by pauleilio** [comment]
Hi,

I have just tested the library and I am not getting the same issue. It would be best to open a support ticket by visiting,
https://4dsystems.com.au/support
It would be interesting to find out what caused the issue.
