### ISSUE TITLE
LedDigitsDisplay crashes when Digits > 10

### ISSUE THREAD

**Issue by L0uisc** [4dsystems/GFX4d#4]
The LedDigitsDisplay function crashes when the Digits parameter passed to it is more than 10. The root cause of the issue is that an `int32_t` is used for `l` in [here](https://github.com/4dsystems/GFX4d/blob/master/src/GFX4d.cpp#L1096). This causes integer overflow when there are 11 digits, because 10^11 > (2^31)-1, with a subsequent crash on the ESP8266.

Do you accept PRs? If so, I can try a fix and submit a PR.

**Comment by L0uisc** [comment]
Can confirm that it does fix my issue to change `int32_t` to `int64_t`.

**Comment by 4dsystems** [comment]
Thank you
